#!/usr/bin/env python3
"""Bake the smac_css_smokefix assets into a SourcePawn include.

The smokefix plugin needs eight small material/model files (models/rxg/*,
materials/rxg/*) present on the server. Rather than shipping them as loose
files next to the .smx, this script embeds their raw bytes as `const` arrays
in an include. Those arrays compile into the plugin's data section, so the
files physically travel inside the .smx and the plugin writes them back to
disk on load (see SmokeVol_ExtractAssets).

Regenerate after changing any asset:

    python3 scripts/gen-smokevol-assets.py

The generated include is committed, so a plain spcomp build needs no extra
step.
"""

import os
import textwrap

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Game-dir-relative destination paths, in the same order smac_css_smokefix.sp
# lists them in g_sDownloads. Each must also be a path under ROOT on disk.
ASSETS = [
    "materials/rxg/smokevol.vmt",
    "materials/rxg/smokevol.vtf",
    "models/rxg/smokevol.dx80.vtx",
    "models/rxg/smokevol.dx90.vtx",
    "models/rxg/smokevol.mdl",
    "models/rxg/smokevol.phy",
    "models/rxg/smokevol.sw.vtx",
    "models/rxg/smokevol.vvd",
]

OUT = os.path.join(
    ROOT, "addons", "sourcemod", "scripting", "include", "smac_smokevol_assets.inc"
)


def ident(path):
    """A SourcePawn identifier for an asset path."""
    return "g_SmokeVolAsset_" + path.replace("/", "_").replace(".", "_")


def byte_array(name, data):
    """Emit `new const name[] = { ... };` wrapped to a sane width."""
    nums = ", ".join(str(b) for b in data)
    body = "\n".join("\t" + line for line in textwrap.wrap(nums, width=96))
    return "new const %s[%d] =\n{\n%s\n};\n" % (name, len(data), body)


def dir_chain(path):
    """Every parent directory of a game-dir-relative file, shallow first."""
    parts = path.split("/")[:-1]
    out = []
    acc = []
    for p in parts:
        acc.append(p)
        out.append("/".join(acc))
    return out


def main():
    lines = []
    lines.append("/**")
    lines.append(" * Embedded smac_css_smokefix assets (materials/rxg, models/rxg).")
    lines.append(" *")
    lines.append(" * GENERATED by scripts/gen-smokevol-assets.py -- do not edit by hand.")
    lines.append(" * The raw file bytes live in the plugin's data section and are written")
    lines.append(" * back to the game directory on load, so the .smx self-extracts them.")
    lines.append(" */")
    lines.append("")
    lines.append("#if defined _smac_smokevol_assets_included")
    lines.append(" #endinput")
    lines.append("#endif")
    lines.append("#define _smac_smokevol_assets_included")
    lines.append("")

    # Collect the directories that must exist, shallow-first, de-duplicated.
    needed_dirs = []
    for path in ASSETS:
        for d in dir_chain(path):
            if d not in needed_dirs:
                needed_dirs.append(d)

    total = 0
    for path in ASSETS:
        with open(os.path.join(ROOT, path), "rb") as f:
            data = f.read()
        total += len(data)
        lines.append("// %s (%d bytes)" % (path, len(data)))
        lines.append(byte_array(ident(path), data))

    # Writes one asset to disk only if it is missing, matching the SourceMod
    # File I/O old-syntax API used throughout this project.
    lines.append("static SmokeVol_WriteAsset(const String:path[], const data[], size)")
    lines.append("{")
    lines.append("\tif (FileExists(path))")
    lines.append("\t\treturn;")
    lines.append("")
    lines.append("\tnew Handle:hFile = OpenFile(path, \"wb\");")
    lines.append("\tif (hFile == INVALID_HANDLE)")
    lines.append("\t{")
    lines.append("\t\tLogError(\"[SMAC] smokefix: could not write embedded asset %s\", path);")
    lines.append("\t\treturn;")
    lines.append("\t}")
    lines.append("")
    lines.append("\tfor (new i = 0; i < size; i++)")
    lines.append("\t\tWriteFileCell(hFile, data[i], 1);")
    lines.append("")
    lines.append("\tCloseHandle(hFile);")
    lines.append("}")
    lines.append("")

    # Public entry point: ensure dirs, then write every asset.
    lines.append("// Writes the embedded smokefix assets to the game directory if missing.")
    lines.append("// Total payload: %d bytes across %d files." % (total, len(ASSETS)))
    lines.append("stock SmokeVol_ExtractAssets()")
    lines.append("{")
    for d in needed_dirs:
        lines.append("\tif (!DirExists(\"%s\"))" % d)
        lines.append("\t\tCreateDirectory(\"%s\", 511);" % d)
    lines.append("")
    for path in ASSETS:
        name = ident(path)
        lines.append(
            "\tSmokeVol_WriteAsset(\"%s\", %s, sizeof(%s));" % (path, name, name)
        )
    lines.append("}")
    lines.append("")

    with open(OUT, "w", newline="\n") as f:
        f.write("\n".join(lines))

    print("Wrote %s (%d asset bytes embedded)" % (os.path.relpath(OUT, ROOT), total))


if __name__ == "__main__":
    main()
